In [16]:
# TASK(a).......................

import pandas as pd
import csv
#for Reading Matrix A from CSV file---------------------------------------------------------

filename = "matrix.csv"
 
# initializing the titles and rows list
fields = []
rows = []
 
# reading csv file
with open(filename, 'r') as csvfile:
    # creating a csv reader object
    csvreader = csv.reader(csvfile)
     
    # extracting field names through first row
    fields = next(csvreader)
 
    # extracting each data row one by one
    for row in csvreader:
        rows.append(row)
print('\n Matrix A is:\n')
for row in rows[:3]:
    # parsing each column of a row
    for col in row:
        print("%10s"%col,end=" "),
    print('\n')
    
#for reading vector matrix from csv file-----------------------------------------------

vector = pd.read_csv("vector.csv")
vector



 Matrix A is:

         3         -2          4 

        -2          6          2 

         4          2          3 



vector b
0         6
1        -4
2        27

In [17]:
# Task(b)............................
import numpy as np
import scipy.linalg as lg
P,L,U = lg.lu(rows)
print("\n Lower Triangular Matrix(L) :\n",L)
print("\n Upper Triangular Matrix(U) :\n",U)
decomposition = P.dot((L.dot(U)))
print("\n After LU decomposition, original matrix is: \n", decomposition)


 Lower Triangular Matrix(L) :
 [[ 1.    0.    0.  ]
 [-0.5   1.    0.  ]
 [ 0.75 -0.5   1.  ]]

 Upper Triangular Matrix(U) :
 [[4.  2.  3. ]
 [0.  7.  3.5]
 [0.  0.  3.5]]

 After LU decomposition, original matrix is: 
 [[ 3. -2.  4.]
 [-2.  6.  2.]
 [ 4.  2.  3.]]


In [20]:
# Task(c)...........................
A = np.asarray(rows, dtype=np.int64)
b = np.asarray(vector, dtype=np.int64)
X = np.linalg.solve(A, b)
print("\n Solution of Linear Equations is:\n")
print(X,"\n")

RankOfMatrix = np.linalg.matrix_rank(A)
#print(RankOfMatrix)

AugmentedMatrix = np.concatenate((A,b),axis=1)
#print(AugmentedMatrix)

RankOfAugmentedMatrix = np.linalg.matrix_rank(AugmentedMatrix)
#print(RankOfAugmentedMatrix)

dimensionOfMatrix =A.shape 
noOfVariables = dimensionOfMatrix[1]
#print(noOfVariables)

if (RankOfMatrix == RankOfAugmentedMatrix and RankOfMatrix==noOfVariables):
     print("System of Linear equations has unique solution")
if (RankOfMatrix == RankOfAugmentedMatrix and RankOfMatrix<noOfVariables):  
    print("System of Linear equations have Infinietly many solutions")
if(RankOfMatrix != RankOfAugmentedMatrix):
    print("System of Linear equations have no solution")


 Solution of Linear Equations is:

[[ 7.42857143]
 [ 2.71428571]
 [-2.71428571]] 

System of Linear equations has unique solution


In [21]:
# Task(d)...........................
import sympy 
from sympy import *  
M=Matrix(A)
print("Matrix : {} ".format(M),"\n")
P, D = M.diagonalize()
print("Diagonal of a matrix : {}".format(D))

Matrix : Matrix([[3, -2, 4], [-2, 6, 2], [4, 2, 3]])  

Diagonal of a matrix : Matrix([[-2, 0, 0], [0, 7, 0], [0, 0, 7]])


In [22]:
# Task(e).............................

#Exponential function on matrix A-----------------------------------------------
print("Exponential function on matrix A: \n")
print(np.exp(A),"\n")

#sine function on matrix A------------------------------------------------------
Sin_Values = np.sin(A)
print("\n Sine function on matrix A: \n")
print ( Sin_Values,"\n")

#sigmoid function on matrix A---------------------------------------------------
from scipy.special import expit
Sigmoid_matrix=expit(A) #expit function is for vectorised sigmoid function in scipy packages
print("\n Sigmoid function on matrix A: \n")
print(Sigmoid_matrix )


Exponential function on matrix A: 

[[2.00855369e+01 1.35335283e-01 5.45981500e+01]
 [1.35335283e-01 4.03428793e+02 7.38905610e+00]
 [5.45981500e+01 7.38905610e+00 2.00855369e+01]] 


 Sine function on matrix A: 

[[ 0.14112001 -0.90929743 -0.7568025 ]
 [-0.90929743 -0.2794155   0.90929743]
 [-0.7568025   0.90929743  0.14112001]] 


 Sigmoid function on matrix A: 

[[0.95257413 0.11920292 0.98201379]
 [0.11920292 0.99752738 0.88079708]
 [0.98201379 0.88079708 0.95257413]]


In [23]:
# Task(f)..................................................

eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues........\n")
print(eigenvalues)
print("\n")
print("Eigenvectors........\n")
print(eigenvectors)

Eigenvalues........

[ 7. -2.  7.]


Eigenvectors........

[[ 0.74535599 -0.66666667 -0.08265645]
 [-0.2981424  -0.33333333  0.92197303]
 [ 0.59628479  0.66666667  0.37833006]]
